typedef enum {_taLeft, _taCenter, _taRight} TTextAlign;

typedef const code struct CScreen TCScreen;
typedef struct MyScreen TMyScreen;

typedef struct  Button_Round {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          *Caption;
  TTextAlign    TextAlign;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          Corner_Radius;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TButton_Round;

typedef const struct  CButton_Round {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  const char          *Caption;
  TTextAlign    TextAlign;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          Corner_Radius;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TCButton_Round;

typedef struct  Label {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          *Caption;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Visible;
  char          Active;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TLabel;

typedef const struct  CLabel {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  const char          *Caption;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Visible;
  char          Active;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TCLabel;

typedef struct  Circle {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Radius;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TCircle;

typedef struct  CircleButton {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Radius;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          *Caption;
  TTextAlign     TextAlign;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TCircleButton;

typedef struct  Box {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TBox;

typedef const struct  CBox {
  unsigned int  OwnerScreenID;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TCBox;

 struct  CScreen {
  unsigned int           Color;
  unsigned int           Width;
  unsigned int           Height;
  unsigned int         ObjectsCount;
  unsigned int           Buttons_RoundCount;
  TButton_Round          * const code *Buttons_Round;
  unsigned int           CButtons_RoundCount;
  TCButton_Round          * const code *CButtons_Round;
  unsigned int           LabelsCount;
  TLabel                 * const code *Labels;
  unsigned int           CLabelsCount;
  TCLabel                 * const code *CLabels;
  unsigned int           CirclesCount;
  TCircle                * const code *Circles;
  unsigned int           CircleButtonsCount;
  TCircleButton          * const code *CircleButtons;
  unsigned int           BoxesCount;
  TBox                   * const code *Boxes;
  unsigned int           CBoxesCount;
  TCBox                   * const code *CBoxes;
};

struct MyScreen {
  unsigned int           Color;
  unsigned int           Width;
  unsigned int           Height;
  unsigned int         ObjectsCount;
  unsigned int           Buttons_RoundCount;
  TButton_Round          * const code *Buttons_Round;
  unsigned int           CButtons_RoundCount;
  TCButton_Round          * const code *CButtons_Round;
  unsigned int           LabelsCount;
  TLabel                 * const code *Labels;
  unsigned int           CLabelsCount;
  TCLabel                 * const code *CLabels;
  unsigned int           CirclesCount;
  TCircle                * const code *Circles;
  unsigned int           CircleButtonsCount;
  TCircleButton          * const code *CircleButtons;
  unsigned int           BoxesCount;
  TBox                   * const code *Boxes;
  unsigned int           CBoxesCount;
  TCBox                   * const code *CBoxes;
};

extern const radScreenID;
extern const izbormeniScreenID;
extern const podesavajScreenID;
extern const lozinkaScreenID;
extern const podesavaParamScreenID;
extern const upuzorenjeScreenID;
extern const podesavanjeSatScreenID;
extern const pozdravScreenID;
extern const podesavanjHronoScreenID;
extern const podesavajKomScreenID;

extern TCScreen * const code CScreens[10];
extern   TCScreen                rad;
extern   TBox                   boksTzad;
extern   TBox                   boksTambijenta;
extern   TBox                   boksTdima;
extern   TCBox                displej;
extern   TCBox                sat;
extern   TCButton_Round          meni;
extern   TLabel                 fazaRada;
extern   TLabel                 vreme;
extern   TCircleButton          minus;
extern   TCircleButton          plus;
extern   TLabel                 zadataT;
extern   TCLabel          TdimaD;
extern   TCLabel          TambijentaD;
extern   TCircleButton          onOff;
extern   TButton_Round          tasterP1;
extern   TButton_Round          tasterP2;
extern   TButton_Round          tasterP3;
extern   TButton_Round          tasterP4;
extern   TButton_Round          tasterP5;
extern   TCircle                krugP1;
extern   TCircle                krugP2;
extern   TCircle                krugP3;
extern   TCircle                krugP4;
extern   TCircle                krugP5;
extern   TLabel                 TD;
extern   TLabel                 TA;
extern   TLabel                 ZTA;
extern   TButton_Round          * const code Screen1_Buttons_Round[5];
extern   TCButton_Round          * const code Screen1_CButtons_Round[1];
extern   TLabel                 * const code Screen1_Labels[6];
extern   TCLabel                 * const code Screen1_CLabels[2];
extern   TCircle                * const code Screen1_Circles[5];
extern   TCircleButton          * const code Screen1_CircleButtons[3];
extern   TBox                   * const code Screen1_Boxes[3];
extern   TCBox                   * const code Screen1_CBoxes[2];


extern   TCScreen                izbormeni;
extern   TCButton_Round          autoRad;
extern   TCButton_Round          podesavanje;
extern   TCButton_Round          hronometar;
extern   TCircleButton          izlaz;
extern   TCButton_Round          manRad;
extern   TCButton_Round          * const code Screen2_CButtons_Round[4];
extern   TCircleButton          * const code Screen2_CircleButtons[1];


extern   TCScreen                podesavaj;
extern   TButton_Round          datumIvreme;
extern   TButton_Round          kalibracija;
extern   TCircleButton          CircleButton1;
extern   TButton_Round          tKomunikacija;
extern   TButton_Round          parametri;
extern   TButton_Round          * const code Screen3_Buttons_Round[4];
extern   TCircleButton          * const code Screen3_CircleButtons[1];


extern   TCScreen                lozinka;
extern   TCBox                disLoz;
extern   TCircle                sh1;
extern   TCircle                sh2;
extern   TCircle                sh3;
extern   TCircle                sh4;
extern   TCButton_Round          ButtonRound1;
extern   TCButton_Round          ButtonRound2;
extern   TCButton_Round          ButtonRound3;
extern   TCButton_Round          ButtonRound5;
extern   TCButton_Round          ButtonRound6;
extern   TCButton_Round          ButtonRound7;
extern   TCButton_Round          ButtonRound8;
extern   TCButton_Round          ButtonRound9;
extern   TCButton_Round          ButtonRound10;
extern   TCircleButton          lozExit;
extern   TCButton_Round          * const code Screen4_CButtons_Round[9];
extern   TCircle                * const code Screen4_Circles[4];
extern   TCircleButton          * const code Screen4_CircleButtons[1];
extern   TCBox                   * const code Screen4_CBoxes[1];


extern   TCScreen                podesavaParam;
extern   TBox                   boksBrojParam;
extern   TBox                   boksVrednostParam;
extern   TCircleButton          paramMinus;
extern   TCircleButton          paramPlus;
extern   TCircleButton          paramNazad;
extern   TCircleButton          paramNapred;
extern   TCircleButton          parExit;
extern   TButton_Round          paramTest;
extern   TCLabel          labelaP;
extern   TLabel                 brojParam;
extern   TLabel                 paramVrednost;
extern   TButton_Round          * const code Screen5_Buttons_Round[1];
extern   TLabel                 * const code Screen5_Labels[2];
extern   TCLabel                 * const code Screen5_CLabels[1];
extern   TCircleButton          * const code Screen5_CircleButtons[5];
extern   TBox                   * const code Screen5_Boxes[2];


extern   TCScreen                upuzorenje;
extern   TBox                   boksGreska;
extern   TLabel                 LabelGR1;
extern   TLabel                 LabelGR2;
extern   TLabel                 LabelGR3;
extern   TLabel                 LabelGR4;
extern   TLabel                 LabelGR5;
extern   TLabel                 LabelGR6;
extern   TLabel                 LabelGR7;
extern   TButton_Round          popravkaButon;
extern   TButton_Round          * const code Screen6_Buttons_Round[1];
extern   TLabel                 * const code Screen6_Labels[7];
extern   TBox                   * const code Screen6_Boxes[1];


extern   TCScreen                podesavanjeSat;
extern   TCircleButton          satExit;
extern   TBox                   boksSati;
extern   TButton_Round          tSatiPlus;
extern   TButton_Round          tsatiMinus;
extern   TLabel                 labelSati;
extern   TBox                   boksMinuti;
extern   TButton_Round          tMinutiPlus;
extern   TButton_Round          tMinutiMinus;
extern   TLabel                 labelMinuti;
extern   TLabel                 dveTacke;
extern   TBox                   boksDani;
extern   TButton_Round          tDaniPlus;
extern   TButton_Round          tDaniMinus;
extern   TLabel                 labelDani;
extern   TBox                   boksMesec;
extern   TButton_Round          tMeseciPlus;
extern   TButton_Round          tMeseciMinus;
extern   TLabel                 labelMesec;
extern   TLabel                 crtica1;
extern   TLabel                 crtica2;
extern   TBox                   boksGodina;
extern   TButton_Round          tGodinaPlus;
extern   TButton_Round          tGodinaMinus;
extern   TLabel                 labelGodina;
extern   TLabel                 god20;
extern   TButton_Round          * const code Screen7_Buttons_Round[10];
extern   TLabel                 * const code Screen7_Labels[9];
extern   TCircleButton          * const code Screen7_CircleButtons[1];
extern   TBox                   * const code Screen7_Boxes[5];


extern   TCScreen                pozdrav;
extern   TLabel                 pozdravPor1;
extern   TLabel                 pozdravPor2;
extern   TLabel                 * const code Screen8_Labels[2];


extern   TCScreen                podesavanjHrono;
extern   TCircleButton          hronoExit;
extern   TBox                   boksDanHrono;
extern   TLabel                 labelHronoDan;
extern   TButton_Round          tHronoProgPlus;
extern   TButton_Round          tHronoProgMinus;
extern   TCLabel          labelProg;
extern   TBox                   boksProgHrono;
extern   TLabel                 labelHronoProg;
extern   TButton_Round          tHronoSatPlus;
extern   TButton_Round          tHronoSatMinus;
extern   TBox                   boksSatHrono;
extern   TLabel                 labelHronoSat;
extern   TButton_Round          tHronoPosoMinus;
extern   TButton_Round          tHronoPosoPlus;
extern   TBox                   boksPosoHrono;
extern   TLabel                 lablHronoPoso;
extern   TButton_Round          tHronoZadTAPlus;
extern   TButton_Round          tHronoZadTAMinus;
extern   TBox                   boksZadTAhrono;
extern   TLabel                 labelHronoZadTA;
extern   TCircleButton          thronoOnOff;
extern   TCLabel          labelHrono;
extern   TCircle                hronoPok;
extern   TButton_Round          * const code Screen9_Buttons_Round[8];
extern   TLabel                 * const code Screen9_Labels[5];
extern   TCLabel                 * const code Screen9_CLabels[2];
extern   TCircle                * const code Screen9_Circles[1];
extern   TCircleButton          * const code Screen9_CircleButtons[2];
extern   TBox                   * const code Screen9_Boxes[5];


extern   TCScreen                podesavajKom;
extern   TCircleButton          exitKom;
extern   TCLabel          labelIP;
extern   TCLabel          labelAdresa;
extern   TBox                   boksIP;
extern   TLabel                 labelAdresiranje;
extern   TCLabel          labelGSM;
extern   TButton_Round          ButtonRound4;
extern   TButton_Round          tIPplus;
extern   TCircle                GSMpok;
extern   TCircleButton          tGSMonOff;
extern   TBox                   bokBrojMob;
extern   TLabel                 labelBorjMob;
extern   TCLabel          labelBrojZaAlarm;
extern   TButton_Round          * const code Screen10_Buttons_Round[2];
extern   TLabel                 * const code Screen10_Labels[2];
extern   TCLabel                 * const code Screen10_CLabels[4];
extern   TCircle                * const code Screen10_Circles[1];
extern   TCircleButton          * const code Screen10_CircleButtons[2];
extern   TBox                   * const code Screen10_Boxes[2];


extern   TMyScreen        CurrentMyScreen;

/////////////////////////
// Events Code Declarations
void cifra1();
void cifra2();
void cifra3();
void cifra4();
void cifra5();
void cifra6();
void cifra7();
void cifra8();
void cifra9();
void danMinus();
void danPlus();
void fKomunikacija();
void godinaMinus();
void godinaPlus();
void GSMonOff();
void hrono();
void hronoOnOff();
void hronoPosoMinus();
void hronoPosoPlus();
void hronoProgMinus();
void hronoProgPlus();
void hronoSatMinus();
void hronoSatPlus();
void hronoZadTAMinus();
void hronoZadTAPlus();
void IPminus();
void IPplus();
void kalibrisi();
void klikMinus();
void klikMinusP();
void klikP1();
void klikP2();
void klikP3();
void klikP4();
void klikP5();
void klikPlus();
void klikPlusP();
void mesecMinus();
void mesecPlus();
void minutiMinus();
void minutiPlus();
void nazad1();
void nazad2();
void nazad3();
void nazadHrono();
void nazadKom();
void nazadP();
void nazadSat();
void paliGasi();
void paramDalje();
void parametrija();
void paramNatrag();
void paramTestDrzanje();
void paramTestiranje();
void paramTestPustanje();
void podesiDiV();
void podUlaz();
void popraviti();
void radAuto();
void radManf();
void satMinus();
void satPlus();
void ulazMeni();
void ispisTemperature (unsigned int temp, TLabel *labela, char* labelaCaption, TBox *boksZaBrisanje);
void Init_Ext_Mem();
void Calibrate();
/////////////////////////

/////////////////////////////////
// Caption variables Declarations
extern char boksTzad_Caption[];
extern char boksTambijenta_Caption[];
extern char boksTdima_Caption[];
extern const char displej_Caption[];
extern const char sat_Caption[];
extern const char meni_Caption[];
extern char fazaRada_Caption[];
extern char vreme_Caption[];
extern char minus_Caption[];
extern char plus_Caption[];
extern char zadataT_Caption[];
extern const char TdimaD_Caption[];
extern const char TambijentaD_Caption[];
extern char onOff_Caption[];
extern char tasterP1_Caption[];
extern char tasterP2_Caption[];
extern char tasterP3_Caption[];
extern char tasterP4_Caption[];
extern char tasterP5_Caption[];
extern char krugP1_Caption[];
extern char krugP2_Caption[];
extern char krugP3_Caption[];
extern char krugP4_Caption[];
extern char krugP5_Caption[];
extern char TD_Caption[];
extern char TA_Caption[];
extern char ZTA_Caption[];
extern const char autoRad_Caption[];
extern const char podesavanje_Caption[];
extern const char hronometar_Caption[];
extern char izlaz_Caption[];
extern const char manRad_Caption[];
extern char datumIvreme_Caption[];
extern char kalibracija_Caption[];
extern char CircleButton1_Caption[];
extern char tKomunikacija_Caption[];
extern char parametri_Caption[];
extern const char disLoz_Caption[];
extern char sh1_Caption[];
extern char sh2_Caption[];
extern char sh3_Caption[];
extern char sh4_Caption[];
extern const char ButtonRound1_Caption[];
extern const char ButtonRound2_Caption[];
extern const char ButtonRound3_Caption[];
extern const char ButtonRound5_Caption[];
extern const char ButtonRound6_Caption[];
extern const char ButtonRound7_Caption[];
extern const char ButtonRound8_Caption[];
extern const char ButtonRound9_Caption[];
extern const char ButtonRound10_Caption[];
extern char lozExit_Caption[];
extern char boksBrojParam_Caption[];
extern char boksVrednostParam_Caption[];
extern char paramMinus_Caption[];
extern char paramPlus_Caption[];
extern char paramNazad_Caption[];
extern char paramNapred_Caption[];
extern char parExit_Caption[];
extern char paramTest_Caption[];
extern const char labelaP_Caption[];
extern char brojParam_Caption[];
extern char paramVrednost_Caption[];
extern char boksGreska_Caption[];
extern char LabelGR1_Caption[];
extern char LabelGR2_Caption[];
extern char LabelGR3_Caption[];
extern char LabelGR4_Caption[];
extern char LabelGR5_Caption[];
extern char LabelGR6_Caption[];
extern char LabelGR7_Caption[];
extern char popravkaButon_Caption[];
extern char satExit_Caption[];
extern char boksSati_Caption[];
extern char tSatiPlus_Caption[];
extern char tsatiMinus_Caption[];
extern char labelSati_Caption[];
extern char boksMinuti_Caption[];
extern char tMinutiPlus_Caption[];
extern char tMinutiMinus_Caption[];
extern char labelMinuti_Caption[];
extern char dveTacke_Caption[];
extern char boksDani_Caption[];
extern char tDaniPlus_Caption[];
extern char tDaniMinus_Caption[];
extern char labelDani_Caption[];
extern char boksMesec_Caption[];
extern char tMeseciPlus_Caption[];
extern char tMeseciMinus_Caption[];
extern char labelMesec_Caption[];
extern char crtica1_Caption[];
extern char crtica2_Caption[];
extern char boksGodina_Caption[];
extern char tGodinaPlus_Caption[];
extern char tGodinaMinus_Caption[];
extern char labelGodina_Caption[];
extern char god20_Caption[];
extern char pozdravPor1_Caption[];
extern char pozdravPor2_Caption[];
extern char hronoExit_Caption[];
extern char boksDanHrono_Caption[];
extern char labelHronoDan_Caption[];
extern char tHronoProgPlus_Caption[];
extern char tHronoProgMinus_Caption[];
extern const char labelProg_Caption[];
extern char boksProgHrono_Caption[];
extern char labelHronoProg_Caption[];
extern char tHronoSatPlus_Caption[];
extern char tHronoSatMinus_Caption[];
extern char boksSatHrono_Caption[];
extern char labelHronoSat_Caption[];
extern char tHronoPosoMinus_Caption[];
extern char tHronoPosoPlus_Caption[];
extern char boksPosoHrono_Caption[];
extern char lablHronoPoso_Caption[];
extern char tHronoZadTAPlus_Caption[];
extern char tHronoZadTAMinus_Caption[];
extern char boksZadTAhrono_Caption[];
extern char labelHronoZadTA_Caption[];
extern char thronoOnOff_Caption[];
extern const char labelHrono_Caption[];
extern char hronoPok_Caption[];
extern char exitKom_Caption[];
extern const char labelIP_Caption[];
extern const char labelAdresa_Caption[];
extern char boksIP_Caption[];
extern char labelAdresiranje_Caption[];
extern const char labelGSM_Caption[];
extern char ButtonRound4_Caption[];
extern char tIPplus_Caption[];
extern char GSMpok_Caption[];
extern char tGSMonOff_Caption[];
extern char bokBrojMob_Caption[];
extern char labelBorjMob_Caption[];
extern const char labelBrojZaAlarm_Caption[];
/////////////////////////////////

void DrawScreen(unsigned int aScreenID);
void DrawRoundButton(TButton_Round *Around_button);
void DrawCRoundButton(TCButton_Round *ACround_button);
void DrawLabel(TLabel *ALabel);
void DrawCLabel(TCLabel *AClabel);
void DrawCircle(TCircle *ACircle);
void DrawCircleButton(TCircleButton *ACircle_button);
void DrawBox(TBox *ABox);
void DrawCBox(TCBox *ACbox);
void Check_TP();
void Start_TP();