/*
 * Project name:
     GorionikInterfejs1.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     8/28/2012
 * Time of creation
     7:20:46 PM
 * Test configuration:
     MCU:             LM3S9B95
     Dev.Board:       EasyMx_PRO_v7_for_Stellaris_ARM
                      http://www.mikroe.com/eng/products/view/792/easymx-pro-v7-for-stellaris-arm/
     Oscillator:      80000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/eng/products/view/752/mikroc-pro-for-arm/
 */

#include "GorionikInterfejs1_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();

  }

}
